/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Impresora */

#ifndef _Included_Impresora
#define _Included_Impresora
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Impresora
 * Method:    envioTimbre
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Impresora_envioTimbre
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
